language: java

dist: bionic

cache:
  directories:
    - $HOME/.m2

jdk:
#  - openjdk8
#  - oraclejdk8
  - openjdk9
  - oraclejdk9
  - openjdk10
  - oraclejdk10
  - openjdk11
  - oraclejdk11
  - openjdk12
  - oraclejdk12
  - openjdk13
  - oraclejdk13
  - openjdk14
  - oraclejdk14

install: skip
script: mvn clean package -Djava.version=${JAVA_VERSION:-8}

jobs:
  include:
#    - jdk: openjdk8
#      script: mvn clean package -Djava.version=8
#      env: JAVA_VERSION=8
#    - jdk: oraclejdk8
#      script: mvn clean package -Djava.version=8
#      env: JAVA_VERSION=8
    - jdk: openjdk9
      script: mvn clean package -Djava.version=9
      env: JAVA_VERSION=9
    - jdk: oraclejdk9
      script: mvn clean package -Djava.version=9
      env: JAVA_VERSION=9
    - jdk: openjdk10
      script: mvn clean package -Djava.version=10
      env: JAVA_VERSION=10
#    - jdk: oraclejdk10
#      script: mvn clean package -Djava.version=10
#      env: JAVA_VERSION=10
    - jdk: openjdk11
      script: mvn clean package -Djava.version=11
      env: JAVA_VERSION=11
    - jdk: oraclejdk11
      script: mvn clean package -Djava.version=11
      env: JAVA_VERSION=11
    - jdk: openjdk12
      script: mvn clean package -Djava.version=12
      env: JAVA_VERSION=12
    - jdk: oraclejdk12
      script: mvn clean package -Djava.version=12
      env: JAVA_VERSION=12
    - jdk: openjdk13
      script: mvn clean package -Djava.version=13
      env: JAVA_VERSION=13
    - jdk: oraclejdk13
      script: mvn clean package -Djava.version=13
      env: JAVA_VERSION=13
    - jdk: openjdk14
      script: mvn clean package -Djava.version=14
      env: JAVA_VERSION=14
    - jdk: oraclejdk14
      script: mvn clean package -Djava.version=14
      env: JAVA_VERSION=14